import Head from 'next/head';
import Header from '../components/Header';
import Feed from '../components/Feed';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import WeatherApp from '../components/WeatherApp';
import { getNews } from '../services/NewsService';
import { useEffect, useState } from 'react';


 export default  function Home() {

  const [ newPosts ,setNewPosts] = useState([]);
  const [ newsCategory ,setNewsCategory] = useState("uganda");
  let componentMounted = true;


  const getData = async () => {

    const { data : localNews } = await getNews(newsCategory);

    // newPosts = localNews.articles;
    // console.log(localNews.articles);

      if(componentMounted){
        setNewPosts( localNews.articles);
      }


      return () => {
        componentMounted = false;
      }

  }

 
// getting new search from the server with a different category
   const newSearch = ( search ) => {
      // console.log(typeof search );
     setNewsCategory(search);

   }

  // fetch data after rendering components in the DOM.
    useEffect(() => {
      getData();
   },[newPosts ,newsCategory]);


  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Best News </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* Rendering  async errors using toastify */}

      <ToastContainer />
     
     {/* Header */}
         <Header onChange = { newSearch  } />

    {/* main section */}

     <main className = {`flex  px-5 md:px-20 flex-col-reverse md:flex-row md:space-x-3 md:justify-between 
           `}>

          {/* Feed */}
          <div className=''>
            <Feed  newPosts = { newPosts }/>
          </div>

          {/* Weather data */}
          <div className=''>
                 <WeatherApp />
          </div>

      </main>

  

    </div>
  );
}



// getting the data from the server.

// export async function getServerSideProps(){ 

//   const data = 
//   await fetch(`https://api.newscatcherapi.com/v2/search?q=uganda`
//   ).then(response => response.json());

//   // After the SERVER has rendered.....
//   //pass the results to the client.
//   return {
//     props:{
//       results: data
//     }
//   }

// }
