import Head from 'next/head';
import Header from '../components/Header';
import Feed from '../components/Feed';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import WeatherApp from '../components/WeatherApp';
import { getLocalNews, getNews } from '../services/NewsService';
import { useEffect, useState } from 'react';


 export default  function Home() {

  const [ newPosts ,setNewPosts] = useState([]);
  const [ newsCategory ,setNewsCategory] = useState("uganda");
  const [ headlines ,setHeadlines ] = useState("Head lines");
  const [mobileplatform  ,setMobilePlatform] = useState(false);
  let componentMounted = true;
  


  const getData = async () => {
    
    let news;
    let newsHeadlines = "";
   

    if(newsCategory === "uganda"){
      const { data :localNews } = await getLocalNews();
      
      news = localNews.articles;
       
      //Get the news headlines
      for(let i = 0; i < localNews.articles.length; i++){
           newsHeadlines += `${ localNews.articles[i].title} |  `; 
      }

      // setting the news headlines
      setHeadlines(newsHeadlines);
      // console.log(headlines);

    }
    else{

      const { data : globalNews } = await getNews(newsCategory);
      news = globalNews.articles;

      //Get the news headlines
      for(let i = 0; i < globalNews.articles.length; i++){
        newsHeadlines += `${ globalNews.articles[i].title} |  `;
      }

      // setting the news headlines
       setHeadlines(newsHeadlines);

    }

    

   // set the statewith current news
    if(componentMounted){
        setNewPosts(news);
    }


      return () => {
        componentMounted = false;
      }

  }

 
// getting new search from the server with a different category
   const newSearch = ( search ) => {
      // console.log(typeof search );
     setNewsCategory(search);

   }

   const setPlatform = (platform) => {
           //console.log(platform);
           setMobilePlatform(platform);
   }

   getData();

  
  
   // fetch data after rendering components in the DOM.
  //   useEffect(() => {
  //     getData();
  //     console.log(newPosts);
  //  },[newPosts ,newsCategory]);


  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title> G-News </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* Rendering  async errors using toastify */}

      <ToastContainer />
     
     {/* Header */}
         <Header onChange = { newSearch  } onPlatform = { setPlatform }/>

    {/* main section */}

     <main className = {`flex  px-5 md:px-20 flex-col md:flex-row md:space-x-3 md:justify-between 
           `}>

          {/* Feed */}
          <div className={ `${ mobileplatform && " hidden"} md:inline-flex`}>
            <Feed  newPosts = { newPosts } headLines = { headlines }/>
          </div>

          {/* Weather data */}
          <div className=' p-3'>
                 <WeatherApp />
          </div>

      </main>

  

    </div>
  );
}



// getting the data from the server.

// export async function getServerSideProps(){ 

//   const data = 
//   await fetch(`https://api.newscatcherapi.com/v2/search?q=uganda`
//   ).then(response => response.json());

//   // After the SERVER has rendered.....
//   //pass the results to the client.
//   return {
//     props:{
//       results: data
//     }
//   }

// }
